FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
	mariadb-server \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/lib/mysql/*

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf 

COPY tools/init.sh /usr/local/bin/init.sh 

RUN chmod +x /usr/local/bin/init.sh 

EXPOSE 3306

ENTRYPOINT ["init.sh"]
